
services:

  webserver:
    image: nginx:1.27.3-alpine
    ports:
      - "5000:80"
    volumes:
      - ./:/app
      - ./nginx.app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  app:
    build: .
    container_name: alorea_app
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    container_name: alorea_db
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - .docker/data/db:/var/lib/mysql
    # healthcheck:
    #   test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8003:80
    environment:
      - PMA_HOST=${DB_HOST} # from .env
      - PMA_PORT=${DB_PORT} # from .env
